[package]
name = "wasm_shader_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
minwebgl = { path="../cg_tools/module/min/minwebgl" }
wasm-bindgen = "0.2"

[profile.release]
lto = true
opt-level = 'z'
strip = true  # Automatically strip symbols from the binary.
codegen-units = 1
